extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.githubpages",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.viewcode",
    "IPython.sphinxext.ipython_directive",
    "IPython.sphinxext.ipython_console_highlighting",
    "matplotlib.sphinxext.plot_directive",
    "numpydoc",
    "sphinx_copybutton",
]

# Configure autosummary
autosummary_generate = True
numpydoc_show_class_members = False
autosummary_imported_members = False  # set True if you want re-exported names

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Soft Mobility"
copyright = "2025, Christophe Eloy"
author = "Christophe Eloy"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
import softmobility

version = softmobility.__version__
release = softmobility.__version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------
html_theme = "sphinx_rtd_theme"
import sphinx_rtd_theme

html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    "**": [
        "relations.html",  # needs 'show_related': True theme option to display
        "searchbox.html",
    ]
}

# -- Options for HTMLHelp output ------------------------------------------
htmlhelp_basename = "soft-mobility"

# -- Options for LaTeX output ---------------------------------------------
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',
    #
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',
    #
    # Additional stuff for the LaTeX preamble.
    # 'preamble': '',
    #
    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

latex_documents = [
    (
        master_doc,
        "soft-mobility.tex",
        "Soft Mobility Documentation",
        "Contributors",
        "manual",
    ),
]

# -- Options for manual page output ---------------------------------------
man_pages = [
    (
        master_doc,
        "soft-mobility",
        "Soft Mobility Documentation",
        [author],
        1,
    )
]

# -- Options for Texinfo output -------------------------------------------
texinfo_documents = [
    (
        master_doc,
        "soft-mobility",
        "Soft Mobility Documentation",
        author,
        "soft-mobility",
        "Python package to compute the mobility of soft body in Stokes flows.",
        "Miscellaneous",
    ),
]

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable", None),
    "jax": ("https://docs.jax.dev/en/latest/", None),
    "sympy": ("https://docs.sympy.org/latest/", None),
    "plotly": ("https://plotly.com/python-api-reference/", None),
    "ipywidgets": ("https://ipywidgets.readthedocs.io/en/latest/", None),
}
